# Generated by Django 5.0.2 on 2024-02-28 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("iu_re", "Regular Employee"),
                            ("iu_sm", "System Manager"),
                            ("iu_sa", "System Administrator"),
                            ("eu_cust", "Customer"),
                            ("eu_mo", "Merchant/Organization"),
                        ],
                        max_length=256,
                    ),
                ),
                ("dob", models.DateField(blank=True, default=None)),
                (
                    "mobile_number",
                    models.CharField(blank=True, default=None, max_length=256),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, default=None, max_length=512),
                ),
                ("city", models.CharField(blank=True, default=None, max_length=128)),
                ("state", models.CharField(blank=True, default=None, max_length=128)),
                ("zip_code", models.CharField(blank=True, default=None, max_length=10)),
                ("country", models.CharField(blank=True, default=None, max_length=256)),
                ("account_created", models.DateTimeField(auto_now_add=True)),
                ("account_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
