# Generated by Django 5.0.2 on 2024-03-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="acc_modification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_handler",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="bankinguser",
            name="pd_modification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankinguser",
            name="user_handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_user",
                to="users.bankinguser",
            ),
        ),
    ]
