# Generated by Django 5.0.2 on 2024-03-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="modification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="bankinguser",
            name="pd_modification_status",
            field=models.CharField(
                blank=True,
                choices=[("rejected", "Rejected"), ("approved", "Approved")],
                max_length=128,
                null=True,
            ),
        ),
    ]
