# Generated by Django 5.0.2 on 2024-02-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[("o", "Open"), ("c", "Close")], default="o", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="closed_on",
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                        ],
                        max_length=128,
                    ),
                ),
                ("initiated", models.DateTimeField(auto_now_add=True)),
                ("status_changed", models.DateTimeField(auto_now=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_account",
                        to="users.account",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_account",
                        to="users.account",
                    ),
                ),
                (
                    "transaction_handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.bankinguser",
                    ),
                ),
            ],
        ),
    ]
