# Generated by Django 5.0.2 on 2024-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_account_acc_modification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankinguser",
            name="pd_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="bankinguser",
            name="user_type",
            field=models.CharField(
                choices=[
                    (1, "System Administrator"),
                    (2, "System Manager"),
                    (3, "Regular Employee"),
                    (4, "Customer"),
                    (5, "Merchant/Organization"),
                ],
                max_length=256,
            ),
        ),
    ]
