# Generated by Django 5.0.2 on 2024-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_account_modification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankinguser",
            name="pd_modification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Waiting for Approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
