# Generated by Django 5.0.2 on 2024-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_bankinguser_pd_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankinguser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("iu_re", "Regular Employee"),
                    ("iu_sm", "System Manager"),
                    ("iu_sa", "System Administrator"),
                    ("eu_cust", "Customer"),
                    ("eu_mo", "Merchant/Organization"),
                ],
                max_length=256,
            ),
        ),
    ]
