# Generated by Django 5.0.2 on 2024-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_bankinguser_deletion_bankinguser_deletion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "transfer"),
                    ("credit", "credit"),
                    ("debit", "debit"),
                ],
                default="Error",
                max_length=128,
            ),
        ),
    ]
