# Generated by Django 5.0.2 on 2024-03-08 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_bankinguser_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankinguser",
            old_name="user_type",
            new_name="usertype",
        ),
    ]
