# Generated by Django 5.0.2 on 2024-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_account_closed_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=128,
            ),
        ),
    ]
