# Generated by Django 5.0.2 on 2024-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_transactions_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="otp",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transactions",
            name="otp_verified",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default="No Action",
                max_length=128,
            ),
        ),
    ]
