# Generated by Django 5.0.2 on 2024-04-06 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_transactions_otp_transactions_otp_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_account_transactions",
                to="users.account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="otp_verified",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="to_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_account_transactions",
                to="users.account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handled_transactions",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                ],
                default="transfer",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("tax_id", models.CharField(max_length=20)),
                ("business_address", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transactions",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.merchantprofile",
            ),
        ),
    ]
