# Generated by Django 5.0.2 on 2024-04-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_transactions_from_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="transactions", name="merchant",),
        migrations.AlterField(
            model_name="transactions",
            name="from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_account",
                to="users.account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="otp_verified",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default="No Action",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="to_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_account",
                to="users.account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_handler",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for approval"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "transfer"),
                    ("credit", "credit"),
                    ("debit", "debit"),
                ],
                default="Error",
                max_length=128,
            ),
        ),
        migrations.DeleteModel(name="MerchantProfile",),
    ]
