# Generated by Django 5.0.2 on 2024-04-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_paymentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="initiated_by_merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_transactions",
                to="users.bankinguser",
            ),
        ),
        migrations.DeleteModel(name="PaymentRequest",),
    ]
