# Generated by Django 5.0.2 on 2024-04-07 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_paymentrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="paymentrequest", name="status",),
        migrations.AddField(
            model_name="paymentrequest",
            name="otp",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="transaction_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="client1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client1_payments",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="client2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client2_payments",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_payments",
                to="users.bankinguser",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("transfer", "Transfer"),
                ],
                max_length=8,
            ),
        ),
    ]
