# Generated by Django 5.0.2 on 2024-04-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_paymentrequest_awaiting_internal_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
