# Generated by Django 5.0.2 on 2024-04-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_usermodificationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="otp_verified",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default="No Action",
                max_length=128,
            ),
        ),
    ]
