# Generated by Django 5.0.2 on 2024-04-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_paymentrequest_otp_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
