# Generated by Django 5.0.2 on 2024-04-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_paymentrequest_otp_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrequest", name="awaiting_internal_approval",
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="client1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client1_payments",
                to="users.account",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="client2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client2_payments",
                to="users.account",
            ),
        ),
    ]
